services:
  - type: web
    name: admin-dashboard
    env: php
    plan: free
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    branch: main
    repo: https://github.com/showyou500/admin-dashboard
    rootDir: .
